-- renomear um ficheiro
ALTER DATABASE [PTC_QS] MODIFY FILE
(NAME=N'FG_PTC_QS_DAT_201612_C1_01',
NEWNAME=N'FG_PTC_QS_DAT_201612_C1_01_remove')    
GO

-- adcionar um ficheiro
ALTER DATABASE [PTC_QS] ADD FILE ( NAME = N'FG_PTC_QS_DAT_201612_C1_01',
       FILENAME = N'V:\PTC_QS_DATA_RLPCLU1_55\PTC_QS\FG_PTC_QS_DAT_201612_C1_01.ndf' , 
       SIZE = 1MB, MAXSIZE = 30GB , FILEGROWTH = 512MB )
       TO FILEGROUP FG_PTC_QS_DAT_201612_C1
GO

-- limpar ficheiro para posterior exclusão
DBCC SHRINKFILE (N'FG_PROD_SERV_SIREL_DAT_201310_H_ABREM', EMPTYFILE)
GO

-- exclusão do ficheiro após ser limpo
ALTER DATABASE [PTC_QS] REMOVE FILE FG_PROD_SERV_SIREL_DAT_201310_H_ABREM 
GO