Use [master]
 
EXEC sp_resetstatus 'GIP'
 
ALTER DATABASE GIP SET EMERGENCY DBCC checkdb('GIP')
 
ALTER DATABASE GIP SET SINGLE_USER WITH ROLLBACK IMMEDIATE
 
DBCC CheckDB('GIP',REPAIR_ALLOW_DATA_LOSS)
 
ALTER DATABASE GIP SET MULTI_USER
 
EXEC sp_resetstatus 'GIP'