--select ps.name PScheme, pf.name PFunction from sys.partition_schemes ps join sys.partition_functions pf on (ps.function_id=pf.function_id)

USE PTC_QS
GO
DECLARE @datacnt as int = 01						--- rever
DECLARE @numdiskdata as int = 46					--- rever
DECLARE @datacnt2 as int = 01						--- rever
DECLARE @numdiskdata2 as int = 46					--- rever
DECLARE @datapath as varchar(max) = 'E:\SQL_DATA_'  --- rever
DECLARE @datapath2 as varchar(max) = 'E:\SQL_DATA_' --- rever
DECLARE @BD AS VARCHAR(150)='PTC_QS'				--- rever
DECLARE @dataf as varchar(max)
DECLARE @dataf2 as varchar(max)
DECLARE @CodData AS VARCHAR(150)
DECLARE @Ano AS VARCHAR(150)
DECLARE @Ano2 AS VARCHAR(150)
DECLARE @AnoMesInicial AS INT=201801				--- rever
DECLARE @AnoMesFinal AS INT=201812					--- rever

PRINT 'USE '+QUOTENAME(@BD)
PRINT 'GO'

DECLARE job_cursor CURSOR FOR  
 SELECT distinct @BD, DateKey/100, DateKey/10000
FROM [msdb] .[dbo].[DimDate]						-- rever
  WHERE DateKey/100 BETWEEN @AnoMesInicial AND @AnoMesFinal
  ORDER BY 1

OPEN job_cursor   
FETCH NEXT FROM job_cursor INTO @BD,@Ano,@Ano2

WHILE @@FETCH_STATUS = 0 
	BEGIN   

		
        if @datacnt <= @numdiskdata
        begin
                if len(@datacnt) = 1 
					set @dataf = LTRIM(RTRIM(@datapath + '0' + cast(@datacnt as char(2))))
					else set @dataf = LTRIM(RTRIM(@datapath + cast(@datacnt as char(2))))
                set @datacnt = @datacnt + 1
					if @datacnt = @numdiskdata + 1
					set @datacnt = 01
		end

		
		if @datacnt2 <= @numdiskdata2
        begin
                if len(@datacnt2) = 1 
					set @dataf2 = LTRIM(RTRIM(@datapath2 + '0' + cast(@datacnt2 as char(2))))
					else set @dataf2 = LTRIM(RTRIM(@datapath2 + cast(@datacnt2 as char(2))))
                set @datacnt2 = @datacnt2 + 1
					if @datacnt2 = @numdiskdata2 + 1
					set @datacnt2 = 01
		end
--startWOT


PRINT 'SET DEADLOCK_PRIORITY HIGH;'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_A]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_C]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_A]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_C]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_A'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_A.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_A]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_C'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_C.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_C]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_A'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_A.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_A]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_C'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_C.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_C]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_H1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_H2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_H2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_H1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_H4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_H4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F3]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F3]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_C1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_C1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F6]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F6]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F5]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F5]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F7]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F7]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F9]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F9]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F8]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F8]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_C1'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_C1.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_C1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F1'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F1.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F2'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F2.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F3'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F3.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F3]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F4'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F4.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F5'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F5.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F5]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F6'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F6.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F6]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F7'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F7.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F7]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F8'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F8.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F8]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F9'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F9.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F9]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_H1'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_H1.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_H1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_H2'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_H2.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_H2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_H4'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_H4.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_H4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_C1'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_C1.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_C1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F1'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F1.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F2'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F2.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F3'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F3.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F3]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F4'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F4.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F4]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F5'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F5.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F5]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F6'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F6.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F6]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F7'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F7.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F7]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F8'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F8.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F8]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F9'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F9.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F9]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_H1'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_H1.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_H1]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_H2'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_H2.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_H2]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_H4'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_H4.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_H4]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F10]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F11]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F12]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F13]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F14]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F15]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F10]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F11]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F12]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F13]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F14]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F15]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F10'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F10.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F10]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F11'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F11.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F11]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F12'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F12.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F12]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F13'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F13.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F13]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F14'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F14.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F14]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_'+@Ano+'_F15'',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_'+@Ano+'_F15.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_'+@Ano+'_F15]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F10'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F10.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F10]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F11'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F11.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F11]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F12'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F12.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F12]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F13'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F13.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F13]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F14'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F14.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F14]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_'+@Ano+'_F15'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_'+@Ano+'_F15.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_'+@Ano+'_F15]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_F_'+@Ano+']'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_F_'+@Ano+']'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_F_'+@Ano+''',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_F_'+@Ano+'.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_F_'+@Ano+']'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_F_'+@Ano+''',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_F_'+@Ano+'.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_F_'+@Ano+']'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_DAT_H4_'+@Ano+']'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PTC_QS_IDX_H4_'+@Ano+']'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_DAT_H4_'+@Ano+''',FILENAME='''+@dataf+'\'+@BD+'\FG_PTC_QS_DAT_H4_'+@Ano+'.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_DAT_H4_'+@Ano+']'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PTC_QS_IDX_H4_'+@Ano+''',FILENAME='''+@dataf2+'\'+@BD+'\FG_PTC_QS_IDX_H4_'+@Ano+'.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PTC_QS_IDX_H4_'+@Ano+']'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_H_NSOM_DAT_'+@Ano+'_H]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_H_NSOM_IDX_'+@Ano+'_H]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_H_NSOM_DAT_'+@Ano+'_H'',FILENAME='''+@dataf+'\'+@BD+'\FG_H_NSOM_DAT_'+@Ano+'_H.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_H_NSOM_DAT_'+@Ano+'_H]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_H_NSOM_IDX_'+@Ano+'_H'',FILENAME='''+@dataf2+'\'+@BD+'\FG_H_NSOM_IDX_'+@Ano+'_H.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_H_NSOM_IDX_'+@Ano+'_H]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_A_ACTIVIDADES_DAT_'+@Ano+'_A]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_A_ACTIVIDADES_IDX_'+@Ano+'_A]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_A_ACTIVIDADES_DAT_'+@Ano+'_A'',FILENAME='''+@dataf+'\'+@BD+'\FG_A_ACTIVIDADES_DAT_'+@Ano+'_A.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_A_ACTIVIDADES_DAT_'+@Ano+'_A]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_A_ACTIVIDADES_IDX_'+@Ano+'_A'',FILENAME='''+@dataf2+'\'+@BD+'\FG_A_ACTIVIDADES_IDX_'+@Ano+'_A.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_A_ACTIVIDADES_IDX_'+@Ano+'_A]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_H_SOLICITACAO_DAT_'+@Ano2+'_H]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_H_SOLICITACAO_IDX_'+@Ano2+'_H]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_H_SOLICITACAO_DAT_'+@Ano2+'_H'',FILENAME='''+@dataf+'\'+@BD+'\FG_H_SOLICITACAO_DAT_'+@Ano2+'_H.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_H_SOLICITACAO_DAT_'+@Ano2+'_H]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_H_SOLICITACAO_IDX_'+@Ano2+'_H'',FILENAME='''+@dataf2+'\'+@BD+'\FG_H_SOLICITACAO_IDX_'+@Ano2+'_H.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_H_SOLICITACAO_IDX_'+@Ano2+'_H]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PROD_SERV_SIREL_DAT_'+@Ano+'_H]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_PROD_SERV_SIREL_IDX_'+@Ano+'_H]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PROD_SERV_SIREL_DAT_'+@Ano+'_H'',FILENAME='''+@dataf+'\'+@BD+'\FG_PROD_SERV_SIREL_DAT_'+@Ano+'_H.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PROD_SERV_SIREL_DAT_'+@Ano+'_H]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_PROD_SERV_SIREL_IDX_'+@Ano+'_H'',FILENAME='''+@dataf2+'\'+@BD+'\FG_PROD_SERV_SIREL_IDX_'+@Ano+'_H.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_PROD_SERV_SIREL_IDX_'+@Ano+'_H]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_ESTADO_REQUISICAO_DAT_'+@Ano+'_F]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILEGROUP [FG_ESTADO_REQUISICAO_IDX_'+@Ano+'_F]'
PRINT 'GO'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_ESTADO_REQUISICAO_DAT_'+@Ano+'_F'',FILENAME='''+@dataf+'\'+@BD+'\FG_ESTADO_REQUISICAO_DAT_'+@Ano+'_F.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_ESTADO_REQUISICAO_DAT_'+@Ano+'_F]'
PRINT 'ALTER DATABASE ['+@BD+'] ADD FILE (NAME=''FG_ESTADO_REQUISICAO_IDX_'+@Ano+'_F'',FILENAME='''+@dataf2+'\'+@BD+'\FG_ESTADO_REQUISICAO_IDX_'+@Ano+'_F.ndf'',SIZE=1MB,MAXSIZE=15GB,FILEGROWTH=256MB) TO FILEGROUP [FG_ESTADO_REQUISICAO_IDX_'+@Ano+'_F]'
PRINT 'GO'
PRINT 'GO'
PRINT 'GO'






--endWOT
        FETCH NEXT FROM job_cursor INTO @BD,@Ano,@Ano2
    END  
CLOSE job_cursor   
DEALLOCATE job_cursor
