--select ps.name PScheme, pf.name PFunction from sys.partition_schemes ps join sys.partition_functions pf on (ps.function_id=pf.function_id)
-- SET 
USE PTC_QS									-- rever
GO
--20121101 até 20130331  
DECLARE @BD AS VARCHAR(150)='PTC_QS'		-- rever
DECLARE @CodData AS VARCHAR(150)
DECLARE @Ano AS VARCHAR(150)
DECLARE @Ano2 AS VARCHAR(150)
DECLARE @AnoMesInicial AS INT=201801		-- rever
DECLARE @AnoMesFinal AS INT=201804			-- rever

DECLARE job_cursor CURSOR FOR  

 SELECT @BD, DateKey/100,DateKey/10000,DateKey
FROM [msdb].[dbo].[DimDate]					-- rever
  WHERE DateKey/100 BETWEEN @AnoMesInicial AND @AnoMesFinal
  ORDER BY 1

OPEN job_cursor   
FETCH NEXT FROM job_cursor INTO @BD,@Ano,@Ano2 ,@CodData  

PRINT 'USE '+quotename(@BD)
PRINT 'GO'
--FG_PTC_LTA_DAT_F_201604_F2
WHILE @@FETCH_STATUS = 0 
    BEGIN   


 --FG_PTC_CG_DAT_201612_F

--startWOT

PRINT 'SET DEADLOCK_PRIORITY HIGH;'
PRINT 'GO'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_A] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_A];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_C] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_C];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_A] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_A];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_C] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_C];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_H1] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_H1];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_H2] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_H2];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_H2] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_H2];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_H1] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_H1];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F1] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F1];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_H4] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_H4];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_H4] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_H4];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F1] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F1];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F2] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F2];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F2] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F2];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F3] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F3];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F3] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F3];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F4] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F4];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F4] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F4];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_C1] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_C1];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_C1] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_C1];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F6] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F6];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F6] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F6];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F5] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F5];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F5] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F5];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F7] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F7];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F7] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F7];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F9] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F9];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F9] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F9];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F8] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F8];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F8] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F8];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F10] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F10];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F11] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F11];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F12] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F12];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F13] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F13];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F14] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F14];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_DAT_F15] NEXT USED [FG_PTC_QS_DAT_'+@Ano+'_F15];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F10] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F10];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F11] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F11];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F12] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F12];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F13] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F13];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F14] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F14];'
PRINT 'ALTER PARTITION SCHEME [PS_DIARIA_IDX_F15] NEXT USED [FG_PTC_QS_IDX_'+@Ano+'_F15];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_DIARIA_F] NEXT USED [FG_PTC_QS_DAT_F_'+@Ano+'];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_DIARIA_F] NEXT USED [FG_PTC_QS_IDX_F_'+@Ano+'];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_DIARIA_H4] NEXT USED [FG_PTC_QS_DAT_H4_'+@Ano+'];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_DIARIA_H4] NEXT USED [FG_PTC_QS_IDX_H4_'+@Ano+'];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_H_NSOM] NEXT USED [FG_H_NSOM_DAT_'+@Ano+'_H];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_H_NSOM] NEXT USED [FG_H_NSOM_IDX_'+@Ano+'_H];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_A_ATIVIDADES] NEXT USED [FG_A_ACTIVIDADES_DAT_'+@Ano+'_A];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_A_ATIVIDADES] NEXT USED [FG_A_ACTIVIDADES_IDX_'+@Ano+'_A];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_H_SOLICITACAO] NEXT USED [FG_H_SOLICITACAO_DAT_'+@Ano2+'_H];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_H_SOLICITACAO] NEXT USED [FG_H_SOLICITACAO_IDX_'+@Ano2+'_H];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_PROD_SERV_SIREL] NEXT USED [FG_PROD_SERV_SIREL_DAT_'+@Ano+'_H];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_PROD_SERV_SIREL] NEXT USED [FG_PROD_SERV_SIREL_IDX_'+@Ano+'_H];'
PRINT 'ALTER PARTITION SCHEME [PS_DAT_ESTADO_REQUISICAO] NEXT USED [FG_ESTADO_REQUISICAO_DAT_'+@Ano+'_F];'
PRINT 'ALTER PARTITION SCHEME [PS_IDX_ESTADO_REQUISICAO] NEXT USED [FG_ESTADO_REQUISICAO_IDX_'+@Ano+'_F];'



--endWOT
            PRINT 'ALTER PARTITION FUNCTION [PARTITION_F_DIARIA]() SPLIT RANGE ('+@CodData+ ')'
            PRINT 'GO'

        FETCH NEXT FROM job_cursor INTO @BD,@Ano ,@Ano2  ,@CodData 
    END  
CLOSE job_cursor   
DEALLOCATE job_cursor


--SELECT pf.name,MIN(prv.value)[MIN],max(prv.value)[MAX]
--  FROM sys.partition_functions pf with(nolock) 
-- INNER JOIN sys.partition_range_values prv with(nolock) ON pf.function_id=prv.function_id
--INNER JOIN sys.partitions p with(nolock) ON p.partition_number = prv.boundary_id
--WHERE pf.name='PARTITION_F_DIARIA'
--GROUP BY pf.name


----select name from sys.filegroups where name like '%_PNP_%'
